version: '2'
services:
  db:
    image: mongo
#    ports:
#      - 27017:27017
    volumes:
      - ./mongo:/data/db
    command: "--smallfiles --logpath=/dev/null"
  web:
    build: ./accessfree-server
#    image: mynode
    ports:
      - "80:3000"
    links:
      - db
  admin:
    build: ./adminMongo
    ports:
      - "1234:1234"
    links:
      - db
